# Generated by Django 3.2.5 on 2021-07-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('image', models.ImageField(upload_to='images/')),
                ('technologies', models.ManyToManyField(blank=True, to='experiences.Technology')),
            ],
        ),
    ]
